In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Airai,TL,2022-01-29 15:29:28,-8.9266,125.4092,60.84,85,100,3.29
1,1,San Cristobal,VE,2022-01-29 15:29:29,7.7669,-72.2250,73.58,39,6,4.41
2,2,Rikitea,PF,2022-01-29 15:29:29,-23.1203,-134.9692,77.07,76,85,11.95
3,3,Saint-Philippe,RE,2022-01-29 15:28:48,-21.3585,55.7679,81.99,85,59,8.59
4,4,Naze,JP,2022-01-29 15:28:49,28.3667,129.4833,55.40,85,100,11.56

In [7]:
sorted_df = city_data_df.sort_values(by="Max Temp")

sorted_df.head(25)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
544,544,Borogontsy,RU,2022-01-29 15:44:04,62.6683,131.1683,-36.36,100,41,0.69
481,481,Sangar,RU,2022-01-29 15:42:38,63.9242,127.4739,-33.34,99,62,2.26
345,345,Ust-Maya,RU,2022-01-29 15:38:43,60.4167,134.5333,-32.89,100,98,0.43
433,433,Verkhoyansk,RU,2022-01-29 15:41:19,67.5447,133.3850,-32.73,100,100,2.33
227,227,Tokur,RU,2022-01-29 15:34:55,53.1333,132.9000,-27.87,100,90,2.24
102,102,Norman Wells,CA,2022-01-29 15:28:06,65.2820,-126.8329,-27.36,68,75,4.61
545,545,Berdigestyakh,RU,2022-01-29 15:44:04,62.0989,126.6992,-23.15,100,100,2.62
331,331,Sosnovo-Ozerskoye,RU,2022-01-29 15:38:36,52.5249,111.5418,-22.77,100,75,3.51
36,36,Zhigansk,RU,2022-01-29 15:29:42,66.7697,123.3711,-21.60,100,96,6.49
195,195,Cherskiy,RU,2022-01-29 15:34:43,68.7500,161.3000,-21.08,100,83,2.30
70,70,Kaa-Khem,RU,2022-01-29 15:30:54,51.6833,94.7333,-20.94,96,26,3.22
250,250,Kungurtug,RU,2022-01-29 15:36:04,50.5994,97.5228,-20.22,98,42,1.52
522,522,Zima,RU,2022-01-29 15:43:55,53.9202,102.0442,-20.09,100,68,1.63
133,133,Saskylakh,RU,2022-01-29 15:30:32,71.9167,114.0833,-19.86,100,100,3.74
355,355,Balagansk,RU,2022-01-29 15:38:47,54.0103,103.0544,-19.82,100,56,0.27
269,269,Batagay-Alyta,RU,2022-01-29 15:36:12,67.8006,130.4114,-17.79,94,31,5.55
218,218,Aklavik,CA,2022-01-29 15:34:52,68.2191,-135.0107,-17.57,69,0,3.44
171,171,Mukhen,RU,2022-01-29 15:33:34,48.1000,136.1000,-16.83,99,92,3.89
440,440,Deputatskiy,RU,2022-01-29 15:41:22,69.3000,139.9000,-16.73,89,99,1.68
343,343,Pangnirtung,CA,2022-01-29 15:38:42,66.1451,-65.7125,-16.60,76,100,9.22
507,507,Belaya Gora,RU,2022-01-29 15:43:49,68.5333,146.4167,-16.11,100,100,2.75
199,199,Tazovskiy,RU,2022-01-29 15:34:45,67.4667,78.7000,-15.99,100,78,6.31
170,170,Seymchan,RU,2022-01-29 15:33:34,62.8833,152.4333,-14.93,97,96,3.78
42,42,Darhan,MN,2022-01-29 15:29:44,49.4867,105.9228,-14.01,99,8,2.89
262,262,Fairbanks,US,2022-01-29 15:36:09,64.8378,-147.7164,-13.99,75,0,0.00

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [12]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []

for temp in max_temp:
    temps.append(max(temp, 0))
    


# Assign the figure variable.
#fig = gmaps.figure()
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2.5)

# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [18]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,San Cristobal,VE,2022-01-29 15:29:29,7.7669,-72.2250,73.58,39,6,4.41
2,2,Rikitea,PF,2022-01-29 15:29:29,-23.1203,-134.9692,77.07,76,85,11.95
3,3,Saint-Philippe,RE,2022-01-29 15:28:48,-21.3585,55.7679,81.99,85,59,8.59
10,10,Busselton,AU,2022-01-29 15:29:31,-33.6500,115.3333,72.09,86,0,16.06
12,12,Vanimo,PG,2022-01-29 15:29:32,-2.6741,141.3028,77.09,90,100,6.67
13,13,Guarapari,BR,2022-01-29 15:29:32,-20.6667,-40.4975,89.49,56,100,16.78
14,14,Nhulunbuy,AU,2022-01-29 15:29:33,-12.2333,136.7667,79.41,89,100,13.80
17,17,Namwala,ZM,2022-01-29 15:29:34,-15.7504,26.4384,76.59,67,84,4.36
20,20,Road Town,VG,2022-01-29 15:29:35,18.4167,-64.6167,82.44,61,20,5.75
24,24,Atuona,PF,2022-01-29 15:28:11,-9.8000,-139.0333,76.73,76,0,12.21

In [32]:
preferred_cities_df = preferred_cities_df.dropna()

preferred_cities_df.sort_values("Country")

#preferred_cities_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
528,528,Luanda,AO,2022-01-29 15:42:09,-8.8368,13.2343,82.40,78,75,9.22
487,487,Benguela,AO,2022-01-29 15:42:41,-12.5763,13.4055,80.96,73,69,9.33
38,38,Namibe,AO,2022-01-29 15:29:42,-15.1961,12.1522,75.52,68,92,12.28
303,303,Necochea,AR,2022-01-29 15:36:05,-38.5473,-58.7368,88.03,37,2,11.54
486,486,Resistencia,AR,2022-01-29 15:37:56,-27.4606,-58.9839,89.10,42,0,9.22
...,...,...,...,...,...,...,...,...,...,...
120,120,Saldanha,ZA,2022-01-29 15:31:46,-33.0117,17.9442,87.85,73,2,24.05
166,166,Port Elizabeth,ZA,2022-01-29 15:33:32,-33.9180,25.5701,79.11,64,20,12.66
17,17,Namwala,ZM,2022-01-29 15:29:34,-15.7504,26.4384,76.59,67,84,4.36
396,396,Sinazongwe,ZM,2022-01-29 15:40:05,-17.2614,27.4618,80.78,75,70,7.29
497,497,Kaputa,ZM,2022-01-29 15:42:44,-8.4689,29.6619,74.08,79,100,0.67

In [33]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
1    San Cristobal      VE     73.58   7.7669  -72.2250
2          Rikitea      PF     77.07 -23.1203 -134.9692
3   Saint-Philippe      RE     81.99 -21.3585   55.7679
10       Busselton      AU     72.09 -33.6500  115.3333
12          Vanimo      PG     77.09  -2.6741  141.3028
13       Guarapari      BR     89.49 -20.6667  -40.4975
14       Nhulunbuy      AU     79.41 -12.2333  136.7667
17         Namwala      ZM     76.59 -15.7504   26.4384
20       Road Town      VG     82.44  18.4167  -64.6167
24          Atuona      PF     76.73  -9.8000 -139.0333

In [ ]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [34]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEAwxmuCvjq9JsNtqoSE_y_s4rcbzhTsFoMAiwWNfXIbZlxCLhv7Mb9lY6EuIDXg1fvhuTmF8x96u09_E6Ukj60kiGwtiCfOH1Dy3eGBRhbm3xRTwmcvyC6H5a-NNvtBR0pX66Pma7LbATuA92I_UWPRlXtZeh0h_vUCzu49Xwr45wvSaM-bZTMCQkcqXKi89Ko06xRMTGJJc9sGbBQsXxaPTjY6_qxxT6A8gvFwBLtqG4JcmroU36B6oCX9pJ1xTcqzThzIB1dAwUGxmaB2DQopYGPGUaWEQnXXLE810kmxpQ1GV02ar8CCvYevYNRC1uAXYUu-iD2OqvMjPg0gbZI6NiTMLN957ZUhlHzaAd3uABxfO498FoN31AVrg8Sq1-twdWzaqogwo61zPlBcCU4Icz6ytWIvN7d9yzdK3SRMlNqTVo4jypX_',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEBneAMnblS2ZxwWvmciHUgJtR8LkMFgtyeUORUnyUe7bMGq0cEQUGZTbRzq2wq7alfQZvIuVVUtDZOIffdbC7sBXIbj-05LaOHNs8nvJVffRaSrWVfbe4XNUMEJArtdEDou7-gx2wFCd_ArNIJJZW7tDF5zOc6t_c_mOopBMcuod-Nc',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 317,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEAXKr3gXq94WbIfpMd6XCkDKPvXTwOejeO0KS6pgii6TNsAqflArn8-5j7O0LMaaD18ZK749HF-mXFwkAwaXZf6BTplA6OJBlY3e0v8FgNMF2WL7_QoejBMUVxIU3fhpFrLoLDxdInSCdyUovhH-7EIMmdDuyC6Oq_XdIgUxa325QTM',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 687,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617746302915,
      'lng': 2.347927730291502},
     'southwest': {'lat': 48.8590766697085, 'lng': 2.345229769708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 853,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEBrBY4e_HjNT6jDMsw2WpPBIHYpsE7swuHp14AWPZMaUK5i1_7X8YWii4WaR_ySeDAye0Dtujfh4F6jwUKmrJja0_XJ-jIixeA8G_CBw71Czwih7DRVtRB_6DNgs3v_055ccUtcKWJH_hmnM-WsZWvMQdE3Q2ZtY-cL8D9HwCRD5UOe',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 890,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEArT-u8CiZqObkTdE0UgEMvJCkyeu5QmwUmS4fy1nRTVOQo0OPuo5oetjuHddhMqzA6JF3nT5W06rohRglafAMn9GZP7YdICnWhBZI2ptcY5VRdiq1D8g9PaVoeQVuoAlEt_Iw0kexgbKXn4kR6PwvyctBxkJQ6HRz-0qUhtKSgyBBg',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2347,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uED3gIqwkiIoJlBgqNsZQ3x8wpeMBNuFT0h9eMQKoy2RECyLTm2B7uKFm5NgOdxjMzsh2bA-ItBiLVxqFMo9vtpCaTGeg5GBs-pUEKBHW6QhKwGH8Ozrglw0PAvZgjUEVgwgQajE4bekvOLE4eLdApFGiZ3-Qt-LDRXu4job3Q7mBPF6',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 284,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEAq6b2MgFmx4SJFZI01cRUD5UCXS5rU17RLzcMsXH2zaMhal7SRy4ai5pqWcJW83Is4GDXuOZswgfNrQkHIQ0VuWNF6Sla4pNcAsAg3KRP2OUgqnC06PMiddO4rhdexe9yylxmb6DY8YL-kf1irL_N8krvWsIlvG8yebzf4E_Y83S2p',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 723,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uECM70MUmHWb1U-zvWPHkdNmTIanwdmhON2k8fy9dIlikRT__DLnM2tNgMAb5S_AfSpZMqfvsj6GJ7kl8HSJBmTu2R_zPza_YVKPMzm2QzSeDQrnlLvaBXk8eyJDlcl1S_SeW977k2ZUIQ4h21lxIiSsImbXn_V0EomEDvwDOYy-pPeb',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 402,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uECR71lsamG4RgAAWfI4n6XhbiYs9Aoh-6fOs89bjULWLWxsXVn0x0jIR70fWC1hWc-Av3mMhvFKteXLaHiaJ8SN96S1-Q4YRWd9wwGRWJiX0ZbBxWSIhTlBLw0A6GVIcugCYlrBnF8753-v3DcQNZk-9lum7zfhzUjKq9XgF4POVTo4',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 510,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uECsRmC7uza-zXQEJb6OvpGveZ6i7bRsXSxwAEgzh1CQ02UGv9ls-WbbZiz-rFUaIjtTtKGC6nD6dm5BCrcQ_ZhFBLWXquvqowAkRqf7KgdiqkIvqM39EMPs6SP4zj9HJjbX09kx4jop8fqyHZxCA71lezssCWawooeJ-PxCYuT5ZFLq',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 858,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEBvQVSvj65dejPfaSHqXhj2t-u5rMCQvssJh3T7GvgPzDVqNpfVO7SaQZw0UT9EzPr0CPx_YkM-AcPeuxjgaVoXXO9BnX20G3JlzuwwEjonzTSbp4a7i0NSB66mnugT64GCRgXU0OPHLmYKkrQq1pO-4cN1DjtanUaMzyR-4_VdiWkR',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.2,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 202,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488820802915,
      'lng': 2.373123430291502},
     'southwest': {'lat': 48.8461841197085, 'lng': 2.370425469708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uEB4qWwrJpnqoyL7ZjC9EUfF8OjT0GvyN0VnpxqZUO0VjNt-zKrK8jMdlbQsZP54EiOQgF_zxeLs0X9sZXST6nIlzzTL_NxNflfgH2i72QUUTNc5IinJqWUL-HRhQFUv_FGGzmw_GknvJV1Efnz--rQ0Gcn0n9NMy8yeUoRzEekwtd4J',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 383,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/106224131803115407650">Marcin Marczak</a>'],
     'photo_reference': 'Aap_uEC5ah8-X4k-73UpSOwh9cfrJOZkTEwwBc_9bdL4NlZihMNBl8av5G33L73lm7mngmsp5pZiO1oNJHK6pVDljzNI-BWSrCUeYGXtZJJqzEI4dqZB9NvWUA437xU4tDXYrmCB-jEWuWJ60KgVTsFEfXCdhd5brrNTcxUpQ-m7YFQ--9V8',
     'width': 3264}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 412,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uECun-t8KgikA37BS13lXeiHatW_13A-0BynGSkdHjIBGAuXdiO-n_p9tNwR7gZ0xmZ7BYmD5A7TVBkD4xTVNJdudFU9K484ye-qXsZF_RqnHoD7juNh62c8-l-I7meW8oZnFRbO-891gwxFXHH28S_47Ri_lx0ol6g72545YaIOUfqS',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 465,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'permanently_closed': True,
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEBtunTO9OpEhyXgvQt3G5scqFL0nkCbBEymPE1ivKFobtWJCHHb-LqT5rGhSRfby7yjaFZpC7il2exYLcP27f3kCmN9zqRK-cQ-6Mr_pfkl6EzEuY_tqX9nqb1bdB7rBoJUejxxqMZCqJ7M8s7m6Fei6EwBU8isrqSwD0QMagKYJJ7B',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1074,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724169302915,
      'lng': 2.340369280291502},
     'southwest': {'lat': 48.8697189697085, 'lng': 2.337671319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [36]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [37]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,San Cristobal,VE,73.58,7.7669,-72.2250,Posada Villaven C.A.
2,Rikitea,PF,77.07,-23.1203,-134.9692,People ThankYou
3,Saint-Philippe,RE,81.99,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
10,Busselton,AU,72.09,-33.6500,115.3333,Observatory Guest House
12,Vanimo,PG,77.09,-2.6741,141.3028,Vahmoneh Lodge Vanimo
...,...,...,...,...,...,...
541,Salta,AR,75.58,-24.7859,-65.4117,Hotel Alejandro I
542,Labuhan,ID,77.90,-6.8844,112.2051,DoubleFAG
543,Miandrivazo,MG,84.61,-19.5167,45.4667,Hôtel Arc En Ciel Miandrivazo
546,Presidente Epitacio,BR,81.27,-21.7633,-52.1156,Hotel Itaverá
552,Moyobamba,PE,78.82,-6.0500,-76.9667,Hospedaje Mariluna

In [38]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [39]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [40]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [41]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))